export const CHECKER_TOTAL_SIMPLE = 36;
export const CHECKER_DIMENSION_SIMPLE = 6;

export const CHECKER_TOTAL_NORMAL = 64;
export const CHECKER_DIMENSION_NORMAL = 8;
export const CHECKER_PIECES_NORMAL = 12;

export const CHECKER_TOTAL_HARD = 100;
export const CHECKER_DIMENSION_HARD = 10;